[build]
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"
  PUBLIC_URL = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200